### ISSUE TITLE
Sync Issue between V3 and V5 basic_info traits

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/member-api#65]
We recently built a member onboarding flow for new members. The onboarding flow uses the v5 member api to create basic_info traits.

Here are some observations :
1. User is taken to the onbaording flow after account activation. https://www.topcoder-dev.com/settings/profile. User enters the following information from the onboarding flow (country, primaryInterestInTopcoder, addresses, shortBio, description). This data is synced to v3 correctly, except for country.
https://platform.topcoder-dev.com/onboard

2. User accesses their settings page. https://www.topcoder-dev.com/settings/profile
User can see the data entered in the onboarding flow (except for country)

3. User edits their information on the settings page(v3 member api)
The following traits are lost in v5 (addresses, description). Here the sync between 

Expected:  Any changes made in v3 member must be synced correctly to v5 member

**Comment by vikasrohit** [comment]
My two cents here, we should not worry about syncing from v3 to v5 considering the near future where we want to discontinue using v3 apis. And if the country is the only field which was not synced correct from v5 to v3 as of now, it might be because of multiple country fields in our system. onboarding flow might be setting home country code, while profile page is looking for competition country code (it can be vice-versa as well). We can debug that and get v5 profile changes reflected in v3 profile pages until we have new profile page which uses the v5 api to be consistent.
fy @rmitchell-iii

**Comment by SathyaJayabal** [comment]
This issue is not fixed as we now use v5 on both the onboarding and settings pages
